id: I4F593999
legacy_id: P003288
ocr_import_info:
  bdrc_scan_id: W29009
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T23:01:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T09:30:43.872259+00:00'
last_modified: 2022-09-02 17:32:20.112495
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29009
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29009
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ངག་དབང་བསྟན་དར།
  author: ཨ་ལག་ཤ་བསྟན་དར།
statistics:
  ocr_word_mean_confidence_index: 0.5527939714377864
  ocr_word_median_confidence_index: 0.550000011920929
quality: null
bases:
  I4980:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4980
      total_pages: 1558
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4980.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5527939714377864
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
