id: P003288
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W29009
  title: གསུང་འབུམ། ངག་དབང་བསྟན་དར
  author: ''
  volumes:
    1a26cbb8f329420285d07d4b93fbae2e:
      image_group_id: I4980
      title: ''
      volume_number: 1
      total_pages: 1558
      base_file: v001.txt
